# Generated by Django 5.1.4 on 2025-01-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_serverconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='geo_images/')),
                ('config_id', models.IntegerField(unique=True)),
                ('location', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='serverconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
