# Generated by Django 5.1.4 on 2025-01-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_geoblock_serverconfig_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='code_time_create',
            field=models.IntegerField(default=0),
        ),
    ]
